# Define the Problem or Question {-#define-problem}
McCrea

**"Extra time to craft a concise yet comprehensive and accurate problem definition pays off..."**  - Smart Choices

The desired state of a [priority resource of concern] ([pROC]) is a decision framed around stakeholder values, and as such, the "problem" with the pROC is actually a decision as well. Since a refuge has already decided that a pROC is important, then there must be underlying reasons for this decision. Why is the [pROC] important? What is the question about the [pROC] that needs to be addressed? Fully answering these questions is arguably one of the most important steps in the survey development process because without this information, we can produce a I&M program that does not address the fundamental information need. 

Framing the problem is often a surprisingly difficult step in the process. We recommend a focused dialogue (i.e., workshop) with team members identified in the [Selecting a pROC][select-proc] step to clarify and document the importance of [pROC]. As the process continues with later steps, the problem statement could evolve.

Specific things to consider include:

##### Importance {-#pROC-importance}
Why is the state about the pROC important? What are the consequences of a poor decision? For example, is there a risk of legal action, extinction of a species or population, impacts to native resources, a loss of hunting opportunities, or not achieving an agency mandate or objective? A [pROC] is, by definition, important to a refuge. In this step, we specify what makes the [pROC] important. This information might be documented already if a refuge has recently gone through a recent ROC prioritization process. In this situation, feel free to use this information (the criteria) to evaluate the [pROC]'s relative importance. Note that the importance of a [pROC] might be a mixture of quantitative criteria (e.g., species status or ecological role) and value judgment (e.g., public enjoyment or financial interest). 

##### Vision of Success {-#vision-success}  
Here we consider what success looks like. To do this, it can be helpful to imagine a hypothetical situation where you had a complete understand of the pROC. What does this situation look like? What is the state of the [pROC]? What attributes about the [pROC] did you consider in your vision?

##### The Decision {-#decision}
What is the decision to be made? What choice or choices does the team face?

##### Scope {-#scope}
How large, broad, or complicated is the problem and the decision about the [pROC]? What is the geographic scope of interest? It is important to frame the problem around this scope. If the scope extends beyond refuge boundaries, it could be valuable to add team members to represent the values of the pROC in this region (e.g., state and tribal biologists). If the scope is only a portion of the refuge, then the team can narrow the focus of the problem.

##### Frequency {-#frequency}
How often does a decision need to be made about the [pROC]? Is there urgency to the decision or is there some flexibility? 

##### Timing {-#timing}
When does a decision need to be made about the [pROC]? Is it a one-time or reoccurring decision? Are there stakeholders that would benefit from a decision on a regular interval? Is there a reoccurring event that demands a decision (e.g., Regional Advisory Committee meetings or Board of Game cycles).

##### Stakeholders {-#id-stakeholders}
Who are the individuals or groups that have a stake in the outcome of the management decision?

##### Authority {-#authority}
Who is able to make decisions that could address the problem?

##### Constraints {-#constraints}
Are there any legal, political or financial constraints? Perceived or real?
