# Gather Information {-#data-mgt}

After you have identified a [pROC] and formed a team to identify the information needs for the [pROC], one of the first steps is manage existing data pertaining to the [pROC]. 
The team will gather relevant data and information, including literature, existing models, refuge data sources (reports, raw data).


## Resources and Guidance

### General Guidance
- [Alaska Region Interim Data Management User Guide](https://ak-region-dst.gitbook.io/alaska-region-interim-data-management-user-guide/)
- [FWS Data Management Handbook](https://doimspp.sharepoint.com/sites/fws-data/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Ffws-data%2FShared%20Documents%2FDataManagementHandbook%2Epdf&parent=%2Fsites%2Ffws-data%2FShared%20Documents)
- [FWS Data Management Sharepoint](https://doimspp.sharepoint.com/sites/fws-data/SitePages/Home.aspx)

### Catalogs and Repositories
- [ServCat](https://ecos.fws.gov/ServCat/)
- [USGS ScienceBase](https://www.sciencebase.gov/catalog/)

### Data Management Plans
- [Alaska Region Data Management Plan Guidance](https://doi.org/10.7944/P9S71Q0W)
- [Alaska Fisheries and Ecological Services Data Management Plan Template](https://ecos.fws.gov/ServCat/Reference/Profile/132238)
- [FWS Data Management Handbook](https://doimspp.sharepoint.com/sites/fws-data/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Ffws-data%2FShared%20Documents%2FDataManagementHandbook%2Epdf&parent=%2Fsites%2Ffws-data%2FShared%20Documents)

### Metadata
- [mdEditor](www.mdeditor.org)
- [mdEditor User Guide](https://guide.mdeditor.org/)
- [mdEditor Tutorial](https://guide.mdeditor.org/tutorial/welcome-to-tutorial.html)
- [Alaska Region Interim Metadata Guide](https://ak-region-dst.gitbook.io/alaska-region-mdeditor-interim-user-guide/)

### Tidy Data
- [Wickham, H. 2014. Tidy Data. Journal of Statistical Software. 59:10.](https://www.jstatsoft.org/index.php/jss/article/view/v059i10/v59i10.pdf)
- [How to Tidy Up Your Data (AK Region Summary)](https://doimspp.sharepoint.com/sites/fws-FF07S00000-data/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Ffws%2DFF07S00000%2Ddata%2FShared%20Documents%2FHow%20To%20Tidy%20Up%20Your%20Data%2Epdf&parent=%2Fsites%2Ffws%2DFF07S00000%2Ddata%2FShared%20Documents)

