# Develop the Conceptual Model {-#concept-model}
Jared

The team, with support from I&M, will sketch out a conceptual model focused on factors that contribute to achieving the conservation goal of the pROC. 

The purpose of a conceptual model is to: 

- Identify potential internal (e.g., vital rates) and external (e.g., environmental drivers, threats, and stressors) key components and management actions that might influence the conservation goal and illustrate the links between key components 
- Increase transparency and communication 
- Build consensus among the team members about how the system operates 
- Identify uncertainties, knowledge gaps and competing hypotheses about how the system operates 
- Provide a framework for a mathematical model 
- Provide a framework for adaptive management (e.g., update the model as new survey data are collected) 

First, the team will gather relevant data and information, including literature, existing models, refuge data sources (reports, raw data). Then, the team will develop a conceptual model based on the pROC conservation goal. Model elements will include environmental and population drivers, threats and management actions. 