# Develop the Mathematical Model {-#math-model}

The team, with support from I&M Technical Team, will translate the conceptual model of the pROC “system” to a mathematical model and parameterize the model with values based on existing data, reported estimates, or solicited professional opinions. 

The purpose of the mathematical model is to: 

- Represent our current understanding of the ecological functioning of the pROC in a quantifiable form, given its conservation and management context expressed through the fundamental objective 
- Organize information for the pROC into a unified, transparent framework that facilitates rapid feedback of new information into management and survey decision making 
- Identify key resource attributes and principal external drivers important to achieving the conservation goal for the pROC 
- Identify candidate specific and measurable means objectives for key resource attributes necessary to achieve conservation goal 
- Determine specific and measurable states or effects of principal external drivers necessary to achieve candidate means objectives 
- If applicable, represent alternatives for a variety of decision problems in a quantifiable form that can be used to identify optimal decisions given predetermined constraints 