# Write SMART Management Objectives {-#mgt-objectives}

Author: Jared

The team, with support from I&M Technical Team, will develop SMART management objectives based on the parameterized mathematical model of the ROC “system”. 

SMART management objectives are considered means objectives in that they are the means by which we achieve our fundamental objective (e.g., Conservation Goal) through management actions.  However, management objectives may differ from broader means objectives (see above) that may not be “achievable” or “results oriented” in the typical context of SMART Refuge management objectives.   

For example, a means objective may be a minimum adult female survival probability of 0.9 to achieve the fundamental objective of maintaining a stable population (i.e., mean population growth rate = 1) for a particular wildlife species.   

If the current knowledge of moose populations shows survival is 0.75 and raising it to the means objective is not achievable, given management time constraints, then setting alternative means objectives that are achievable and have high likelihood of contributing to the broader means objective should be considered. 

 The purpose of a SMART management objective: 

- Specific: identifies a clearly defined resource attribute targeted by a specific management action. 
- Measurable: defines the expected outcome of a specific management action with numerical values expressed in a mathematical statement. 
- Achievable: communicates a practical management action that is feasible given the fundamental objective, possible other means objectives, and logistical and other decision constraints. 
- Results-Oriented: presents clear expectations for the outcomes of proposed management actions contributing to the fundamental objective. 
- Time-Limited: specifies start and end dates for initiation, implementation, completion, expected outcomes, and evaluation of management actions.  