# Glossary {-#glossary}

##### conceptual model {-#conceptual-model}
A diagram that shows the best understanding of key system components, including contributing factors and potential management actions, and their relationship to the fundamental objective.


##### conservation objective {-#conservation-objective}


##### contributing factor {-#contributing-factor}
A component in a conceptual model that along with other contributing factors depict what is driving changes in the state of a system and the fundamental objective.

##### fundamental objective {-#fundamental-objective}
Descriptive, open-ended, and often broad statement of desired future conditions that conveys a purpose, but does not define measurable units. The primary (end) objective that reflects what is most important to the stakeholders and can be achieved through means objectives.

##### goal {-#goal}
See [fundamental objective].

##### means objective {-#means-objective}
A way of achieving a [fundamental objective]. 

##### management objective {-#management-objective}
A concise statement of what we want to achieve, how much we want to achieve, when and where we want to achieve it, and who is responsible for the work.

##### management action {-#management-action}
An activity intended to help achieve a [means objective].

##### PRIMR (Planning and Review of I&M activities on Refuges){-#primr}
A database to store and retrieve information about survey activites occurring on refuge lands.

##### priority resource of concern {-#priority-resource-of-concern}
A refuge [resource of concern] that has been selected for survey development.


##### pROC {-#proc} 
See [priority resource of concern].


##### resource of concern {-#resource-of-concern}
High priority plant and/or animal species, species groups, or communities at a refuge that have been identified using a prioritization process (e.g., [Identifying Refuge Resources of Concern](https://ecos.fws.gov/ServCat/DownloadFile/7679?Reference=7935)).  

##### results chain {-#results-chain}


##### ServCat {-#servcat}
The **Ser**vice **Cat**alog. A web application that compiles documents and organizes data, such as reports, surveys, databases, geospatial data and images.

##### SMART {-#smart} 
**S**pecific, **M**easurable, **A**chievable, **R**esults-oriented, and **T**ime-fixed. Defined in ["Writing Refuge Management Goals and Objectives"](https://www.fws.gov/refuges/policiesandbudget/pdfs/writingrefugegoals_022504.pdf).

##### stakeholder {-#stakeholders}
Individuals or groups that have a stake in the outcome of the management decision.

##### survey {-#survey}