# Document and Archive {-#document}

Author: McCrea

The final step will be to archive the data, products, and metadata generated from this effort in ServCat. All data and products will be documented with mdEditor metadata records (JSON files) that follow the regional metadata product profile. The data and products will include: 

- A final report (PDF) describing the results of the “Defining the Problem” step, a description and figure of the conceptual model, and tables of management objectives 
- A conceptual model that displays factors contributing to conservation goal of the pROC (PDF or XML file) 
- A mathematical model that quantifies the relative contributions of the conceptual model’s attributes (e.g., environmental factors, population parameters, and management actions) to the state of the pROC (the conservation goal) (R and/or Jags files)
- PRIMR records that list and describe surveys selected to inform the status of the management objectives for the pROC 
- Source datasets for parameterizing the mathematical models (CSV) 
- An IMP that includes the survey(s) identified above 